#include "dustytypes.h"
#include "ile_accd.h"
#include "pkind.h"

const BYTE bno_tbl[160]={
	pkind_noun,				/*   1 ¿Í¡¦Æ°Êª¡¦¿ÍÌ¾ */
	pkind_noun,				/*   2 ²ñ¼Ò¡¦µ¡´ØÌ¾¡¦¹ñÌ¾ */
	pkind_noun,				/*   3 Êª¡¦ºàÎÁ */
	pkind_noun,				/*   4 »ş */
	pkind_noun,				/*   5 ¾ì½ê¡¦ÃÏÌ¾ */
	pkind_noun,				/*   6 ¿ô */
	pkind_noun,				/*   7 Ãê¾İÌ¾»ì */
	pkind_noun,				/*   8 ¹ÔÆ° */
	pkind_digit,			/*   9 ¿ô»ú */
	pkind_noun,				/*  10 ÂçÏÂ¸ÀÍÕÌ¾»ì */
	pkind_noun,				/*  11 Ì¾»ì */
	pkind_noun,				/*  12 Ì¾»ì */
	pkind_noun,				/*  13 Ì¾»ì */
	pkind_others,			/*  14 ÆÃ¼ìµ­¹æ */
	pkind_ren,				/*  15 Ï¢ÂÎ»ì */
	pkind_ren,				/*  16 ¤ÎÏ¢ÂÎ»ì */
	pkind_ren,				/*  17 ¤¢¤ëÏ¢ÂÎ»ì */
	pkind_ren,				/*  18 ¤ó¤ÊÏ¢ÂÎ»ì */
	pkind_adjv,				/*  19 ·ÁÍÆÆ°»ì */
	pkind_adjv,				/*  20 ·ÁÍÆÆ°»ì¡¦Åª */
	pkind_adjv,				/*  21 ·ÁÍÆÆ°»ì¡¦É÷ */
	pkind_adjv,				/*  22 ·ÁÍÆÆ°»ì */
	pkind_adjv,				/*  23 ·ÁÍÆÆ°»ì */
	pkind_adjv,				/*  24 ·ÁÍÆÆ°»ì */
	pkind_adjv,				/*  25 ·ÁÍÆÆ°»ì */
	pkind_adv,				/*  26 Éû»ì */
	pkind_adv,				/*  27 Éû»ì */
	pkind_adv,				/*  28 Éû»ì */
	pkind_adv,				/*  29 Éû»ì */
	pkind_adv,				/*  30 Éû»ì */
	pkind_adv,				/*  31 Éû»ì */
	pkind_adv,				/*  32 ´¶Æ°»ì */
	pkind_adv,				/*  33 Éû»ì */
	pkind_adv,				/*  34 Éû»ì */
	pkind_verb_stem,		/*  35 Æ°»ì¸ì´´ */
	pkind_verb_stem,		/*  36 Æ°»ì¸ì´´ */
	pkind_verb_stem,		/*  37 Æ°»ì¸ì´´ */
	pkind_verb_stem,		/*  38 Æ°»ì¸ì´´ */
	pkind_verb_stem,		/*  39 Æ°»ì¸ì´´ */
	pkind_verb_stem,		/*  40 Æ°»ì¸ì´´ */
	pkind_verb_stem,		/*  41 Æ°»ì¸ì´´ */
	pkind_verb_stem,		/*  42 Æ°»ì¸ì´´ */
	pkind_verb_stem,		/*  43 Æ°»ì¸ì´´ */
	pkind_verb_stem,		/*  44 Æ°»ì¸ì´´ */
	pkind_verb_stem,		/*  45 Æ°»ì¸ì´´ */
	pkind_verb_stem,		/*  46 Æ°»ì¸ì´´ */
	pkind_verb_stem,		/*  47 Æ°»ì¸ì´´ */
	pkind_verb_stem,		/*  48 Æ°»ì¸ì´´ */
	pkind_verb_sa,			/*  49 ¥µÊÑÌ¾»ì·Á */
	pkind_verb_stem,		/*  50 Æ°»ì¸ì´´ */
	pkind_verb_stem,		/*  51 Æ°»ì¸ì´´ */
	pkind_particle,			/*  52 ³ÈÄ¥½õ»ì */
	pkind_adj_stem,			/*  53 ·ÁÍÆ»ì¸ì´´ */
	pkind_adj_stem,			/*  54 ·ÁÍÆ»ì¸ì´´ */
	pkind_aux_verb,			/*  55 ÂÇ¾Ã½õÆ°»ì¸ì´´ */
	pkind_adj_stem,			/*  56 ·ÁÍÆ»ì¸ì´´ */
	pkind_adj_stem,			/*  57 ·ÁÍÆ»ì¸ì´´ */
	pkind_adj_stem,			/*  58 ·ÁÍÆ»ì¸ì´´ */
	pkind_adj_stem,			/*  59 ·ÁÍÆ»ì¸ì´´ */
	pkind_noun,				/*  60 Ì¾»ì¡¦Ä¹²»ÀÜÂ³ */
	pkind_pref,				/*  61 ¿ÍÌ¾Àè¹Ô»ì */
	pkind_pref,				/*  62 prefix */
	pkind_pref,				/*  63 prefix */
	pkind_pref,				/*  64 prefix ¡Ö¤ª¡×*/
	pkind_pref,				/*  65 prefix */
	pkind_pref,				/*  66 prefix ¡ÖÂè¡×,¡Ö¿Ş¡×,¡ÖÉ½¡×*/
	pkind_pref,				/*  67 prefix */
	pkind_pref,				/*  68 prefix */
	pkind_pref,				/*  69 prefix */
	pkind_pref,				/*  70 prefix */
	pkind_pref,				/*  71 prefix */
	pkind_pref,				/*  72 prefix */
	pkind_particle,			/*  73 ½õ»ì */
	pkind_particle,			/*  74 ½õ»ì */
	pkind_particle,			/*  75 ½õ»ì */
	pkind_particle,			/*  76 ½õ»ì */
	pkind_particle,			/*  77 ½õ»ì */
	pkind_particle,			/*  78 ½õ»ì */
	pkind_particle,			/*  79 ½õ»ì */
	pkind_particle,			/*  80 ½õ»ì */
	pkind_particle,			/*  81 ½õ»ì */
	pkind_particle,			/*  82 ½õ»ì */
	pkind_particle,			/*  83 ½õ»ì */
	pkind_particle,			/*  84 ½õ»ì */
	pkind_particle,			/*  85 ½õ»ì */
	pkind_particle,			/*  86 ½õ»ì */
	pkind_particle,			/*  87 ½õ»ì */
	pkind_particle,			/*  88 ½õ»ì */
	pkind_particle,			/*  89 ½õ»ì */
	pkind_particle,			/*  90 ½õ»ì */
	pkind_particle,			/*  91 ½õ»ì */
	pkind_particle,			/*  92 ½õ»ì */
	pkind_particle,			/*  93 ½õ»ì */
	pkind_particle,			/*  94 ½õ»ì */
	pkind_particle,			/*  95 ½õ»ì */
	pkind_particle,			/*  96 ½õ»ì */
	pkind_particle,			/*  97 ½õ»ì */
	pkind_particle,			/*  98 ½õ»ì */
	pkind_particle,			/*  99 ½õ»ì */
	pkind_particle,			/* 100 ½õ»ì */
	pkind_particle,			/* 101 ½õ»ì */
	pkind_particle,			/* 102 ½õ»ì */
	pkind_particle,			/* 103 ½õ»ì */
	pkind_particle,			/* 104 ½õ»ì */
	pkind_particle,			/* 105 ½õ»ì */
	pkind_particle,			/* 106 ½õ»ì */
	pkind_particle,			/* 107 ½õ»ì */
	pkind_particle,			/* 108 ½õ»ì */
	pkind_particle,			/* 109 ½õ»ì */
	pkind_particle,			/* 110 ½õ»ì */
	pkind_particle,			/* 111 ½õ»ì */
	pkind_particle,			/* 112 ½õ»ì */
	pkind_particle,			/* 113 ½õ»ì */
	pkind_particle,			/* 114 ½õ»ì */
	pkind_particle,			/* 115 ½õ»ì */
	pkind_particle,			/* 116 ½õ»ì */
	pkind_aux_verb,			/* 117 ½õÆ°»ì */
	pkind_aux_verb,			/* 118 ½õÆ°»ì */
	pkind_aux_verb,			/* 119 ½õÆ°»ì */
	pkind_aux_verb,			/* 120 ½õÆ°»ì */
	pkind_aux_verb,			/* 121 ½õÆ°»ì */
	pkind_aux_verb,			/* 122 ½õÆ°»ì */
	pkind_aux_verb,			/* 123 ½õÆ°»ì */
	pkind_aux_verb,			/* 124 ½õÆ°»ì */
	pkind_aux_verb,			/* 125 ½õÆ°»ì */
	pkind_aux_verb,			/* 126 ½õÆ°»ì */
	pkind_aux_verb,			/* 127 ½õÆ°»ì */
	pkind_aux_verb,			/* 128 ½õÆ°»ì */
	pkind_aux_verb,			/* 129 ½õÆ°»ì */
	pkind_aux_verb,			/* 130 ½õÆ°»ì */
	pkind_aux_verb,			/* 131 ½õÆ°»ì */
	pkind_aux_verb,			/* 132 ½õÆ°»ì */
	pkind_aux_verb,			/* 133 ½õÆ°»ì */
	pkind_aux_verb,			/* 134 ½õÆ°»ì */
	pkind_aux_verb,			/* 135 ½õÆ°»ì */
	pkind_aux_verb,			/* 136 ½õÆ°»ì */
	pkind_aux_verb,			/* 137 ½õÆ°»ì */
	pkind_aux_verb,			/* 138 ½õÆ°»ì */
	pkind_verb_inflect,		/* 139 Æ°»ì³èÍÑ¸ìÈø */
	pkind_verb_renyou,		/* 140 Æ°»ìÏ¢ÍÑ·Á³èÍÑ¸ìÈø */
	pkind_verb_inflect,		/* 141 Æ°»ì³èÍÑ¸ìÈø */
	pkind_verb_inflect,		/* 142 Æ°»ì³èÍÑ¸ìÈø */
	pkind_verb_inflect,		/* 143 Æ°»ì³èÍÑ¸ìÈø */
	pkind_verb_inflect,		/* 144 Æ°»ì³èÍÑ¸ìÈø */
	pkind_verb_inflect,		/* 145 Æ°»ì³èÍÑ¸ìÈø */
	pkind_verb_inflect,		/* 146 Æ°»ì³èÍÑ¸ìÈø */
	pkind_verb_inflect,		/* 147 Æ°»ì³èÍÑ¸ìÈø */
	pkind_verb_inflect,		/* 148 Æ°»ì³èÍÑ¸ìÈø */
	pkind_verb_inflect,		/* 149 Æ°»ì³èÍÑ¸ìÈø */
	pkind_verb_inflect,		/* 150 Æ°»ì³èÍÑ¸ìÈø */
	pkind_verb_inflect,		/* 151 Æ°»ì³èÍÑ¸ìÈø */
	pkind_verb_inflect,		/* 152 Æ°»ì³èÍÑ¸ìÈø */
	pkind_verb_inflect,		/* 153 Æ°»ì³èÍÑ¸ìÈø */
	pkind_verb_inflect,		/* 154 Æ°»ì³èÍÑ¸ìÈø */
	pkind_adj_inflect,		/* 155 ·ÁÍÆ»ì³èÍÑ¸ìÈø */
	pkind_adj_inflect,		/* 156 ·ÁÍÆ»ì³èÍÑ¸ìÈø */
	pkind_adj_inflect,		/* 157 ·ÁÍÆ»ì³èÍÑ¸ìÈø */
	pkind_adj_inflect,		/* 158 ·ÁÍÆ»ì³èÍÑ¸ìÈø */
	pkind_adj_inflect,		/* 159 ·ÁÍÆ»ì³èÍÑ¸ìÈø */
	pkind_adj_inflect		/* 160 ·ÁÍÆ»ì³èÍÑ¸ìÈø */
};

/* End of ile_accd.c */
