[Info]
Name=
Type=CompDef
Version=2.10.000

[Program Files\DECtalk Single Dlls For All Languages\Italian System DLL]
OBJECT=No
DESCRIPTION=
STATUS=
VISIBLE=No
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=ITS
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=650EC9B3-272F-4FFA-9924-217AF7D62CE4
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Single Language Italian system DLL
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Components]
component0=Program Files\DECtalk Single Dlls For All Languages\Italian System DLL
component1=Program Files\DECtalk For English UK
component2=Program Files\DECtalk For Latin American Spanish
component3=Program Files\DECtalk Single Dlls For All Languages\French System DLL
component4=Program Files\DECtalk Single Dlls For All Languages\German System DLL
component5=Program Files\DECtalk Single Dlls For All Languages\English US System DLL
component6=Program Files\Sample Programs\Dtmemory
component7=Program Files\License Key
component8=Program Files\Sample Programs\Programs Source Code\Multi Language Demo
component9=Program Files\Sample Programs\Programs Source Code\Windic Source
component10=Program Files\Sample Programs\Windic
component11=Program Files\DECtalk For German
component12=Program Files\Sample Programs
component13=Program Files\Sample Programs\Vercheck
component14=Program Files\DECtalk VB
component15=Program Files\DECtalk For Castilian Spanish
component16=Program Files\DECtalk For French
component17=Program Files
component18=Include Files
component19=Program Files\DECtalk Single Dlls For All Languages
component20=Program Files\DECtalk Single Dlls For All Languages\Latin American Spanish System DLL
component21=DECtalk
component22=Program Files\DECtalk For English US
component23=Program Files\Sample Programs\Programs Source Code\Dtmemory Source
component24=Program Files\Sample Programs\Programs Source Code\Vercheck Source
component25=Installation Files
component26=Program Files\Sample Programs\Say
component27=Program Files\Help Files
component28=Program Files\Sample Programs\Programs Source Code\Dtsample Source
component29=Program Files\Sample Programs\Programs Source Code
component30=Program Files\Sample Programs\Dtsample
component31=Program Files\Sample Programs\Ttstest
component32=Program Files\DECtalk Single Dlls For All Languages\English UK System DLL
component33=Program Files\DECtalk for Italian
component34=Program Files\Sample Programs\Programs Source Code\Say Source
component35=Documentation
component36=Program Files\DECtalk Multi Language Support
component37=Program Files\DECtalk Single Dlls For All Languages\Castilian Spanish System DLL
component38=Program Files\Sample Programs\Multi Language Demo

[Program Files\DECtalk For English UK]
OBJECT=No
DESCRIPTION=Installs the English UK version of DECtalk.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=UK
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=22571b20-63d4-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=DECtalk Folder English UK Dictionary Files
filegroup1=DECtalk Speech English UK System Files
filegroup2=Directory for English UK
filegroup3=Multi Language English UK System DLLs
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\DECtalk For Latin American Spanish]
OBJECT=No
DESCRIPTION=Installs the Latin American Spanish version of DECtalk.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=LA
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=22571b23-63d4-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=DECtalk Folder Latin American Dictionary Files
filegroup1=DECtalk Speech Latin American Spanish System Files
filegroup2=Directory for Latin American Spanish
filegroup3=Multi Language Latin American Spanish System DLLs
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\DECtalk Single Dlls For All Languages\French System DLL]
OBJECT=No
DESCRIPTION=
STATUS=
VISIBLE=No
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=FRS
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=a8d3f7df-0694-11d5-9cb8-0060081ea1c6
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Single Language French system DLL
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\DECtalk Single Dlls For All Languages\German System DLL]
OBJECT=No
DESCRIPTION=
STATUS=
VISIBLE=No
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=GRS
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=05a96ece-63dc-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Single Language German system DLL
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\DECtalk Single Dlls For All Languages\English US System DLL]
OBJECT=No
DESCRIPTION=
STATUS=
VISIBLE=No
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=USS
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=05a96ecd-63dc-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Single Language English US system DLL
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\Sample Programs\Dtmemory]
OBJECT=No
DESCRIPTION=This application creates audio data (PCM Data).
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=dtmemory
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=22571b25-63d4-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Sample Program Dtmemory Executable Only
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\License Key]
OBJECT=No
DESCRIPTION=This program increases your license count by three.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=license
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=92e3d2a1-b3f7-11d4-9c8f-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=License Key
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\Sample Programs\Programs Source Code\Multi Language Demo]
OBJECT=No
DESCRIPTION=This application demonstrates the various language dll's for DECtalk.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=mldemo
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=22571b2e-63d4-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Sample Application Multi Language Demo With Source
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\Sample Programs\Programs Source Code\Windic Source]
OBJECT=No
DESCRIPTION=This sample application creates user define dictionary entries for DECtalk. 
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=3edca8af-67fb-11d4-9c78-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Sample Application Windic With Source
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\Sample Programs\Windic]
OBJECT=No
DESCRIPTION=This sample application creates user define dictionary entries for DECtalk. 
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=windic
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=2dd0efdb-6481-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Sample Program Windic Executable Only
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\DECtalk For German]
OBJECT=No
DESCRIPTION=Installs the German version of DECtalk.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=GR
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=22571b22-63d4-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=DECtalk Folder German Dictionary Files
filegroup1=DECtalk Speech German System Files
filegroup2=Directory for German
filegroup3=Multi Language German System DLLs
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\Sample Programs]
OBJECT=No
DESCRIPTION=This contains both the sample applications executables and source code
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=166a5bb5-67af-11d4-9c78-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
member0=Program Files\Sample Programs\Programs Source Code
member1=Program Files\Sample Programs\Dtmemory
member2=Program Files\Sample Programs\Dtsample
member3=Program Files\Sample Programs\Multi Language Demo
member4=Program Files\Sample Programs\Say
member5=Program Files\Sample Programs\Ttstest
member6=Program Files\Sample Programs\Vercheck
member7=Program Files\Sample Programs\Windic
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\Sample Programs\Vercheck]
OBJECT=No
DESCRIPTION=This application checks the current version of DECtalk.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=vercheck
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=2dd0efd8-6481-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Sample Program Vercheck Executable Only
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\DECtalk VB]
OBJECT=No
DESCRIPTION=Install Visual Basic Wrapper for Dectalk
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=VB
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=88B9AEE8-CB9B-494F-989B-7196876A9CC7
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Sample Application Visual Basic
filegroup1=VB DEF
filegroup2=VB FR
filegroup3=VB GR
filegroup4=VB IT
filegroup5=VB LA
filegroup6=VB SP
filegroup7=VB UK
filegroup8=VB US
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\DECtalk For Castilian Spanish]
OBJECT=No
DESCRIPTION=Installs the Castilian Spanish version of DECtalk.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=SP
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=22571b1f-63d4-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=DECtalk Folder Castilian Spanish Dictionary Files
filegroup1=DECtalk Speech Castilian Spanish System Files
filegroup2=Directory for Castilian Spanish
filegroup3=Multi Language Castilian Spanish System DLLs
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\DECtalk For French]
OBJECT=No
DESCRIPTION=This will nstall the Beta French version of DECtalk.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=FR
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=a8d3f7e0-0694-11d5-9cb8-0060081ea1c6
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=DECtalk Folder French Dictionary Files
filegroup1=Directory for French
filegroup2=Multi Language French System DLLs
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files]
OBJECT=No
DESCRIPTION=
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=dc316b25-63d3-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
member0=Program Files\DECtalk For Castilian Spanish
member1=Program Files\DECtalk For English UK
member2=Program Files\DECtalk For English US
member3=Program Files\DECtalk For French
member4=Program Files\DECtalk For German
member5=Program Files\DECtalk For Latin American Spanish
member6=Program Files\DECtalk Multi Language Support
member7=Program Files\DECtalk Single Dlls For All Languages
member8=Program Files\Sample Programs
member9=Program Files\License Key
member10=Program Files\DECtalk VB
member11=Program Files\Help Files
member12=Program Files\DECtalk for Italian
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Include Files]
OBJECT=No
DESCRIPTION=
STATUS=
VISIBLE=No
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=include
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=22571b32-63d4-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Include
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\DECtalk Single Dlls For All Languages]
OBJECT=No
DESCRIPTION=
STATUS=
VISIBLE=No
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=f94f89f5-b017-11d4-9c8e-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
member0=Program Files\DECtalk Single Dlls For All Languages\Castilian Spanish System DLL
member1=Program Files\DECtalk Single Dlls For All Languages\French System DLL
member2=Program Files\DECtalk Single Dlls For All Languages\German System DLL
member3=Program Files\DECtalk Single Dlls For All Languages\English UK System DLL
member4=Program Files\DECtalk Single Dlls For All Languages\English US System DLL
member5=Program Files\DECtalk Single Dlls For All Languages\Latin American Spanish System DLL
member6=Program Files\DECtalk Single Dlls For All Languages\Italian System DLL
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\DECtalk Single Dlls For All Languages\Latin American Spanish System DLL]
OBJECT=No
DESCRIPTION=
STATUS=
VISIBLE=No
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=LAS
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=05a96ecf-63dc-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Single Language Latin American system DLL
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[DECtalk]
OBJECT=No
DESCRIPTION=
STATUS=
VISIBLE=No
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=bf519f8f-67cb-11d4-9c78-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=DECtalk Folder
filegroup1=DECtalk Speech System Files
filegroup2=DECtalk SystemsTtsserv Executable For Windows Directory
HANDLERONInstalling=
HANDLERONInstalled=DECtalk_Installed
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\DECtalk For English US]
OBJECT=No
DESCRIPTION=Installs the English US version of DECtalk.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=US
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=22571b21-63d4-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=DECtalk Folder English US Dictionary Files
filegroup1=DECtalk Speech English US System Files
filegroup2=Directory for English US
filegroup3=Multi Language English US Spanish System DLLs
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\Sample Programs\Programs Source Code\Dtmemory Source]
OBJECT=No
DESCRIPTION=This application creates audio data (PCM Data).
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=dtmemory
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=22571b2c-63d4-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Sample Application Dtmemory With Source
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\Sample Programs\Programs Source Code\Vercheck Source]
OBJECT=No
DESCRIPTION=This application checks the version of the current dll's installed.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=vercheck
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=2dd0efd9-6481-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Sample Application Vercheck With Source
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Installation Files]
OBJECT=No
DESCRIPTION=
STATUS=
VISIBLE=No
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=606d8156-dc37-11d4-9c9b-0060081ea1c6
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Install Files
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\Sample Programs\Say]
OBJECT=No
DESCRIPTION=This is a command line version of the speak application.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=say
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=22571b2a-63d4-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=DECtalk System Say  Executable For Windows Directory
filegroup1=Sample Program Say Executable Only
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\Help Files]
OBJECT=No
DESCRIPTION=This contains the help files for DECtalk.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=help
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=dc316b27-63d3-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Documentation
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\Sample Programs\Programs Source Code\Dtsample Source]
OBJECT=No
DESCRIPTION=This is a trim down version of our speak application.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=dtmemory
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=22571b2d-63d4-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Sample Application Dtsample With Source
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\Sample Programs\Programs Source Code]
OBJECT=No
DESCRIPTION=This installs the source code for the sample programs.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=22571b2b-63d4-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
member0=Program Files\Sample Programs\Programs Source Code\Dtmemory Source
member1=Program Files\Sample Programs\Programs Source Code\Dtsample Source
member2=Program Files\Sample Programs\Programs Source Code\Multi Language Demo
member3=Program Files\Sample Programs\Programs Source Code\Say Source
member4=Program Files\Sample Programs\Programs Source Code\Vercheck Source
member5=Program Files\Sample Programs\Programs Source Code\Windic Source
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\Sample Programs\Dtsample]
OBJECT=No
DESCRIPTION=This is a trim down version of our speak application.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=dtsample
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=22571b26-63d4-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Sample Program Dtsample Executable Only
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\Sample Programs\Ttstest]
OBJECT=No
DESCRIPTION=This is a SAPI sample apllication.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=ttstest
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=22571b29-63d4-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Sample Application Ttstest Without Source
filegroup1=Sample Program Ttstest Executable Only
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\DECtalk Single Dlls For All Languages\English UK System DLL]
OBJECT=No
DESCRIPTION=
STATUS=
VISIBLE=No
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=UKS
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=05a96e97-63dc-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Single Language English Uk system DLL
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\DECtalk for Italian]
OBJECT=No
DESCRIPTION=Installs the Italian version of DECtalk
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=IT
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=1D60B77C-9E3B-430B-8020-0BDDBB885CB0
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=DECtalk Folder Italian Dictionary Files
filegroup1=Directory for Italian
filegroup2=Multi Language Italian System DLLs
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\Sample Programs\Programs Source Code\Say Source]
OBJECT=No
DESCRIPTION=This is a command line version of the speak application.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=say
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=22571b2f-63d4-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Sample Application Say With Source
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Documentation]
OBJECT=No
DESCRIPTION=This contains all the text files including the readme.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=dd1a4812-649a-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Documentation
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\DECtalk Multi Language Support]
OBJECT=No
DESCRIPTION=
STATUS=
VISIBLE=No
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=MultLang
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=22571b24-63d4-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Directory for Multi Language
filegroup1=Multi Language System DLLs
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\DECtalk Single Dlls For All Languages\Castilian Spanish System DLL]
OBJECT=No
DESCRIPTION=
STATUS=
VISIBLE=No
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=SPS
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=22571b31-63d4-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Single Language Castilian Spanish system DLL
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[Program Files\Sample Programs\Multi Language Demo]
OBJECT=No
DESCRIPTION=This application demonstrates the various language dll's for DECtalk.
STATUS=
VISIBLE=Yes
DISK=ANYDISK
FILENEED=STANDARD
INCLUDEINBUILD=Yes
PASSWORD=
ENCRYPT=No
COMPRESSIFSEPARATE=No
UNINSTALLABLE=Yes
COMMENT=
DEFSELECTION=Yes
SELECTED=Yes
IMAGE=
TARGETDIRCDROM=mldemo
DISPLAYTEXT=
HTTPLOCATION=
FTPLOCATION=
MISC=
GUID=22571b27-63d4-11d4-9c75-0060083e4df1
_SPLIT_BEFORE=
_SPLIT_AFTER=
_DATAASFILES=
_NO_SPLIT=
_NO_SPLIT_BEFORE=
VOLATILE=
filegroup0=Sample Program Multi Language Executable Only
HANDLERONInstalling=
HANDLERONInstalled=
HANDLERONUnInstalling=
HANDLERONUnInstalled=

[TopComponents]
component0=Program Files
component1=Include Files
component2=Documentation
component3=DECtalk
component4=Installation Files

[SetupType]
setuptype0=Full Installation
setuptype1=Custom

[SetupTypeItem-Full Installation]
Comment=
Descrip=Installs the entire software for DECtalk
DisplayText=
item0=Program Files\DECtalk Single Dlls For All Languages\Italian System DLL
item1=Program Files\DECtalk Single Dlls For All Languages\German System DLL
item2=Program Files\DECtalk Single Dlls For All Languages\French System DLL
item3=Program Files\DECtalk For Latin American Spanish
item4=Program Files\DECtalk For English UK
item5=Program Files\DECtalk Single Dlls For All Languages\English US System DLL
item6=Program Files\Sample Programs\Dtmemory
item7=Program Files\License Key
item8=Program Files\Sample Programs\Windic
item9=Program Files\Sample Programs\Programs Source Code\Windic Source
item10=Program Files\Sample Programs\Programs Source Code\Multi Language Demo
item11=Program Files\Sample Programs
item12=Program Files\DECtalk For German
item13=Program Files\Sample Programs\Vercheck
item14=Program Files\DECtalk VB
item15=Program Files\DECtalk For Castilian Spanish
item16=Program Files\DECtalk For French
item17=Program Files\DECtalk Single Dlls For All Languages
item18=Program Files
item19=Include Files
item20=Program Files\DECtalk Single Dlls For All Languages\Latin American Spanish System DLL
item21=DECtalk
item22=Program Files\DECtalk For English US
item23=Program Files\Sample Programs\Programs Source Code\Vercheck Source
item24=Program Files\Sample Programs\Programs Source Code\Dtmemory Source
item25=Installation Files
item26=Program Files\Sample Programs\Say
item27=Program Files\Help Files
item28=Program Files\Sample Programs\Ttstest
item29=Program Files\Sample Programs\Dtsample
item30=Program Files\Sample Programs\Programs Source Code\Dtsample Source
item31=Program Files\Sample Programs\Programs Source Code
item32=Program Files\DECtalk Single Dlls For All Languages\English UK System DLL
item33=Program Files\DECtalk for Italian
item34=Program Files\Sample Programs\Programs Source Code\Say Source
item35=Program Files\DECtalk Multi Language Support
item36=Program Files\DECtalk Single Dlls For All Languages\Castilian Spanish System DLL
item37=Program Files\Sample Programs\Multi Language Demo
item38=Documentation

[SetupTypeItem-Custom]
Comment=
Descrip=Allows user to pick and choice which components to install
DisplayText=
item0=Program Files\DECtalk Single Dlls For All Languages\Italian System DLL
item1=Program Files\DECtalk Single Dlls For All Languages\German System DLL
item2=Program Files\DECtalk Single Dlls For All Languages\French System DLL
item3=Program Files\DECtalk For Latin American Spanish
item4=Program Files\DECtalk For English UK
item5=Program Files\DECtalk Single Dlls For All Languages\English US System DLL
item6=Program Files\Sample Programs\Dtmemory
item7=Program Files\License Key
item8=Program Files\Sample Programs\Windic
item9=Program Files\Sample Programs\Programs Source Code\Windic Source
item10=Program Files\Sample Programs\Programs Source Code\Multi Language Demo
item11=Program Files\Sample Programs
item12=Program Files\DECtalk For German
item13=Program Files\Sample Programs\Vercheck
item14=Program Files\DECtalk VB
item15=Program Files\DECtalk For Castilian Spanish
item16=Program Files\DECtalk For French
item17=Program Files\DECtalk Single Dlls For All Languages
item18=Program Files
item19=Include Files
item20=Program Files\DECtalk Single Dlls For All Languages\Latin American Spanish System DLL
item21=DECtalk
item22=Program Files\DECtalk For English US
item23=Program Files\Sample Programs\Programs Source Code\Vercheck Source
item24=Program Files\Sample Programs\Programs Source Code\Dtmemory Source
item25=Installation Files
item26=Program Files\Sample Programs\Say
item27=Program Files\Help Files
item28=Program Files\Sample Programs\Ttstest
item29=Program Files\Sample Programs\Dtsample
item30=Program Files\Sample Programs\Programs Source Code\Dtsample Source
item31=Program Files\Sample Programs\Programs Source Code
item32=Program Files\DECtalk Single Dlls For All Languages\English UK System DLL
item33=Program Files\DECtalk for Italian
item34=Program Files\Sample Programs\Programs Source Code\Say Source
item35=Program Files\DECtalk Single Dlls For All Languages\Castilian Spanish System DLL
item36=Program Files\Sample Programs\Multi Language Demo
item37=Documentation
item38=Program Files\DECtalk Multi Language Support

