<html>
<body>
<pre>
<h1>Build Log</h1>
<h3>
--------------------Configuration: CE - Win32 (WCE x86em) Release German--------------------
</h3>
<h3>Command Lines</h3>
Creating temporary file "C:\DOCUME~1\build\LOCALS~1\Temp\RSP10CB.tmp" with contents
[
/nologo /W3 /I ".\ce" /I ".\acna" /I ".\api" /I ".\cmd" /I ".\lts" /I ".\ph" /I ".\vtm" /I ".\kernel" /I ".\nt" /I ".\include" /I ".\protos" /I "..\.." /D "NDEBUG" /D "STRICT" /D "_WIN32_WCE_EMULATION" /D "INTERNATIONAL" /D "USA" /D "INTLMSG_CODEPAGE" /D "x86" /D "i486" /D "_X86_" /D "GERMAN" /D _WIN32_WCE=211 /D UNDER_CE=211 /D "UNICODE" /D "WIN32" /D "BLD_DECTALK_DLL" /D "STATIC_BUILD" /D "WIN32_PLATFORM_HPCPRO" /D "_UNICODE" /Fp"..\.\build\cestatic\x86em\gr\release\link/CE.pch" /YX /Fo"..\.\build\cestatic\x86em\gr\release\link/" /Zm200 /Gz /c 
"D:\work\PRODUCT\dapi\src\LTS\LSA_ADJU.C"
"D:\work\PRODUCT\dapi\src\LTS\lsa_coni.c"
"D:\work\PRODUCT\dapi\src\LTS\lsa_util.c"
"D:\work\PRODUCT\dapi\src\PH\ph_aloph.c"
"D:\work\PRODUCT\dapi\src\PH\ph_claus.c"
"D:\work\PRODUCT\dapi\src\PH\ph_draw.c"
"D:\work\PRODUCT\dapi\src\PH\ph_drwt0.c"
"D:\work\PRODUCT\dapi\src\PH\Ph_drwt02it.c"
"D:\work\PRODUCT\dapi\src\PH\ph_inton.c"
"D:\work\PRODUCT\dapi\src\PH\Ph_inton2.c"
"D:\work\PRODUCT\dapi\src\PH\Ph_inton2it.c"
"D:\work\PRODUCT\dapi\src\PH\ph_main.c"
"D:\work\PRODUCT\dapi\src\PH\ph_romi.c"
"D:\work\PRODUCT\dapi\src\PH\ph_setar.c"
"D:\work\PRODUCT\dapi\src\PH\ph_sort.c"
"D:\work\PRODUCT\dapi\src\PH\ph_syl.c"
"D:\work\PRODUCT\dapi\src\PH\ph_task.c"
"D:\work\PRODUCT\dapi\src\PH\ph_timng.c"
"D:\work\PRODUCT\dapi\src\PH\ph_vdefi.c"
"D:\work\PRODUCT\dapi\src\PH\ph_vset.c"
"D:\work\PRODUCT\dapi\src\PH\phinit.c"
"D:\work\PRODUCT\dapi\src\NT\spc.c"
"D:\work\PRODUCT\dapi\src\VTM\sync.c"
"D:\work\PRODUCT\dapi\src\API\ttsapi.c"
"D:\work\PRODUCT\dapi\src\VTM\vtm.c"
"D:\work\PRODUCT\dapi\src\VTM\vtmiont.c"
]
Creating command line "cl.exe @C:\DOCUME~1\build\LOCALS~1\Temp\RSP10CB.tmp" 
Creating temporary file "C:\DOCUME~1\build\LOCALS~1\Temp\RSP10CC.tmp" with contents
[
/nologo /out:".\..\build\cestatic\x86em\gr\release\dtstatic.lib" 
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\acxf1c.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\brent.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\circuit.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\cm_char.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\cm_cmd.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\cm_copt.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\cm_main.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\cm_pars.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\cm_phon.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\cm_text.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\cm_util.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\Cmd_init.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\cmd_wav.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\CRYPT2.OBJ
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\dbgwins.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\DECSTD97.OBJ
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\diffuse.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\hlframe.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\inithl.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\loaddict.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\log10table.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ls_chari.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ls_dict.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ls_homo.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ls_math.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ls_proc.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ls_spel.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ls_speli.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ls_suff.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ls_suffi.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\LSA_ADJU.OBJ
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\lsa_coni.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\lsa_fr.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\lsa_gr.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\lsa_ir.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\lsa_it.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\lsa_ja.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\lsa_rtbi.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\lsa_rule.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\lsa_sl.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\lsa_sp.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\lsa_task.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\lsa_us.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\lsa_util.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\lsw_main.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\mmalloc.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\nasalf1x.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\opthread.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\par_ambi.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\par_char.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\par_dict.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\par_pars.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\par_rule.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ph_aloph.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ph_claus.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ph_draw.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ph_drwt0.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\Ph_drwt02it.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ph_inton.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\Ph_inton2.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\Ph_inton2it.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ph_main.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ph_romi.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ph_setar.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ph_sort.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ph_syl.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ph_syntx.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ph_task.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ph_timng.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ph_vdefi.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ph_vset.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\phinit.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\phlog.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\pipe.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\playaud.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\playtone.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\services.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\spc.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\sqrttable.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\sync.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\ttsapi.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\Usa_init.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\vtm.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\vtmiont.obj
\work\PRODUCT\dapi\build\cestatic\x86em\gr\release\link\wince.obj
]
Creating command line "link.exe -lib @C:\DOCUME~1\build\LOCALS~1\Temp\RSP10CC.tmp"
<h3>Output Window</h3>
Compiling...
LSA_ADJU.C
lsa_coni.c
lsa_util.c
.\ph\ph_prot.h(150) : warning C4028: formal parameter 1 different from declaration
.\ph\ph_prot.h(154) : warning C4028: formal parameter 1 different from declaration
ph_aloph.c
ph_claus.c
D:\work\PRODUCT\dapi\src\PH\ph_claus.c(341) : warning C4013: 'phintonit' undefined; assuming extern returning int
D:\work\PRODUCT\dapi\src\PH\ph_claus.c(489) : warning C4013: 'pht0drawit' undefined; assuming extern returning int
ph_draw.c
ph_drwt0.c
Ph_drwt02it.c
ph_inton.c
Ph_inton2.c
D:\work\PRODUCT\dapi\src\PH\ph_inton1.c(1771) : warning C4761: integral size mismatch in argument; conversion supplied
Ph_inton2it.c
D:\work\PRODUCT\dapi\src\PH\Ph_inton2.c(1307) : warning C4761: integral size mismatch in argument; conversion supplied
D:\work\PRODUCT\dapi\src\PH\Ph_inton2.c(1334) : warning C4761: integral size mismatch in argument; conversion supplied
D:\work\PRODUCT\dapi\src\PH\Ph_inton2.c(1339) : warning C4761: integral size mismatch in argument; conversion supplied
D:\work\PRODUCT\dapi\src\PH\Ph_inton2it.c(1559) : warning C4047: 'function' : 'short *' differs in levels of indirection from 'short ** '
D:\work\PRODUCT\dapi\src\PH\Ph_inton2it.c(1559) : warning C4024: 'make_f0_command_it' : different types for formal and actual parameter 7
D:\work\PRODUCT\dapi\src\PH\Ph_inton2it.c(1600) : warning C4047: 'function' : 'short ' differs in levels of indirection from 'short *'
D:\work\PRODUCT\dapi\src\PH\Ph_inton2it.c(1600) : warning C4024: 'make_f0_command_it' : different types for formal and actual parameter 8
D:\work\PRODUCT\dapi\src\PH\Ph_inton2it.c(1571) : warning C4101: 'length' : unreferenced local variable
ph_main.c
D:\work\PRODUCT\dapi\src\PH\Ph_inton2it.c(1193) : warning C4761: integral size mismatch in argument; conversion supplied
D:\work\PRODUCT\dapi\src\PH\Ph_inton2it.c(1600) : warning C4761: integral size mismatch in argument; conversion supplied
D:\work\PRODUCT\dapi\src\PH\Ph_inton2it.c(1621) : warning C4761: integral size mismatch in argument; conversion supplied
D:\work\PRODUCT\dapi\src\PH\ph_main.c(342) : warning C4013: 'calloc' undefined; assuming extern returning int
ph_romi.c
ph_setar.c
D:\work\PRODUCT\dapi\src\PH\p_it_st1.c(1482) : warning C4101: 'temp' : unreferenced local variable
ph_sort.c
ph_syl.c
D:\work\PRODUCT\dapi\src\PH\ph_sort.c(594) : warning C4761: integral size mismatch in argument; conversion supplied
D:\work\PRODUCT\dapi\src\PH\ph_sort.c(1536) : warning C4761: integral size mismatch in argument; conversion supplied
ph_task.c
ph_timng.c
ph_vdefi.c
ph_vset.c
D:\work\PRODUCT\dapi\src\PH\ph_vset.c(754) : warning C4018: '>' : signed/unsigned mismatch
phinit.c
spc.c
sync.c
D:\work\PRODUCT\dapi\src\VTM\sync.c(337) : warning C4244: '=' : conversion from 'unsigned long ' to 'unsigned short ', possible loss of data
D:\work\PRODUCT\dapi\src\VTM\sync.c(338) : warning C4244: '=' : conversion from 'unsigned long ' to 'unsigned short ', possible loss of data
ttsapi.c
D:\work\PRODUCT\dapi\src\API\ttsapi.c(2037) : warning C4013: 'calloc' undefined; assuming extern returning int
D:\work\PRODUCT\dapi\src\API\ttsapi.c(5163) : warning C4133: 'function' : incompatible types - from 'unsigned short *' to 'const char *'
D:\work\PRODUCT\dapi\src\API\ttsapi.c(5163) : warning C4133: 'function' : incompatible types - from 'unsigned short *' to 'const char *'
D:\work\PRODUCT\dapi\src\API\ttsapi.c(8252) : warning C4550: expression evaluates to a function which is missing an argument list
This is NOT a USERDIC_COMPILE
D:\work\PRODUCT\dapi\src\API\ttsapi.c(11519) : warning C4047: '=' : 'struct LANG_ENTRY *' differs in levels of indirection from 'int '
D:\work\PRODUCT\dapi\src\API\ttsapi.c(11737) : warning C4133: 'function' : incompatible types - from 'unsigned short *' to 'char *'
vtm.c
D:\work\PRODUCT\dapi\src\VTM\vtm3.c(486) : warning C4101: 'temp3' : unreferenced local variable
D:\work\PRODUCT\dapi\src\VTM\vtm3.c(2064) : warning C4018: '>' : signed/unsigned mismatch
D:\work\PRODUCT\dapi\src\VTM\vtm3.c(2077) : warning C4018: '>' : signed/unsigned mismatch
vtmiont.c
D:\work\PRODUCT\dapi\src\VTM\vtmiont.c(494) : warning C4013: 'calloc' undefined; assuming extern returning int
D:\work\PRODUCT\dapi\src\VTM\vtmiont.c(3322) : warning C4305: '=' : truncation from 'const double ' to 'float '
Creating library...



<h3>Results</h3>
dtstatic.lib - 0 error(s), 34 warning(s)
</pre>
</body>
</html>
